#!/usr/bin/env python3
"""Generate deterministic firmware-resident PocketArcade application data."""

import argparse
import gzip
import json
import re
from pathlib import Path


APP_ID = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,46}[a-z0-9])?$")
COMPRESSED_SUFFIXES = {".css", ".js", ".json", ".svg"}
IGNORED_SUFFIXES = {".zip"}
MIME = {
    ".css": "text/css; charset=utf-8",
    ".gif": "image/gif",
    ".html": "text/html; charset=utf-8",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json",
    ".lua": "text/plain; charset=utf-8",
    ".mp3": "audio/mpeg",
    ".ogg": "audio/ogg",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
}


def c_bytes(data: bytes) -> str:
    return "\n".join(
        "    " + ", ".join(f"0x{byte:02x}" for byte in data[start : start + 16]) + ","
        for start in range(0, len(data), 16)
    )


def safe_relative(path: Path) -> str:
    relative = path.as_posix()
    parts = path.parts
    if (
        not relative
        or len(relative) > 96
        or path.is_absolute()
        or any(part in {"", ".", ".."} for part in parts)
    ):
        raise ValueError(f"unsafe built-in app path: {relative}")
    return relative


def load_app(directory: Path) -> tuple[str, list[tuple[str, str, str | None, bytes]]]:
    directory = directory.resolve()
    manifest_path = directory / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    app_id = manifest.get("id")
    if not isinstance(app_id, str) or not APP_ID.fullmatch(app_id):
        raise ValueError(f"{manifest_path}: invalid application id")
    if directory.name.lower() != app_id:
        raise ValueError(f"{manifest_path}: directory and application id differ")

    files = [manifest_path]
    for root_name in ("client", "server", "assets"):
        root = directory / root_name
        if root.exists():
            files.extend(path for path in root.rglob("*") if path.is_file())

    entries = []
    seen = set()
    for source in sorted(files):
        if source.is_symlink() or source.suffix.lower() in IGNORED_SUFFIXES:
            continue
        relative = safe_relative(source.relative_to(directory))
        if relative in seen:
            continue
        seen.add(relative)
        raw = source.read_bytes()
        if not raw:
            raise ValueError(f"{source}: built-in app files must not be empty")
        browser_asset = relative != "manifest.json" and not relative.startswith("server/")
        encoding = (
            "gzip"
            if browser_asset and source.suffix.lower() in COMPRESSED_SUFFIXES
            else None
        )
        prepared = (
            gzip.compress(raw, compresslevel=9, mtime=0) if encoding else raw
        )
        mime = MIME.get(source.suffix.lower(), "application/octet-stream")
        entries.append((relative, mime, encoding, prepared))

    required = {
        "manifest.json",
        manifest.get("client", {}).get("entrypoint"),
        manifest.get("runtime", {}).get("entrypoint"),
    }
    stylesheet = manifest.get("client", {}).get("stylesheet")
    if stylesheet:
        required.add(stylesheet)
    missing = sorted(path for path in required if path and path not in seen)
    if missing:
        raise ValueError(f"{manifest_path}: missing referenced files: {', '.join(missing)}")
    return app_id, entries


def generate(app_directories: list[Path], output: Path) -> None:
    apps = [load_app(directory) for directory in app_directories]
    ids = [app_id for app_id, _ in apps]
    if len(set(ids)) != len(ids):
        raise ValueError("built-in application ids must be unique")

    parts = [
        "/* Generated by tools/prepare_builtin_apps.py. Do not edit. */",
        '#include "builtin_apps.h"',
        "",
        "#include <string.h>",
        "",
    ]
    records = []
    asset_index = 0
    for app_id, entries in apps:
        for relative, mime, encoding, data in entries:
            symbol = f"builtin_app_file_{asset_index}"
            parts.extend(
                [
                    f"static const unsigned char {symbol}[] = {{",
                    c_bytes(data),
                    "};",
                    "",
                ]
            )
            encoding_literal = f'"{encoding}"' if encoding else "NULL"
            records.append(
                f'    {{ "{app_id}", "{relative}", "{mime}", '
                f"{encoding_literal}, {symbol}, sizeof({symbol}) }},"
            )
            asset_index += 1

    parts.extend(
        [
            "static const char *const builtin_app_ids[] = {",
            *(f'    "{app_id}",' for app_id in ids),
            "};",
            "",
            "static const pa_builtin_app_file_t builtin_app_files[] = {",
            *records,
            "};",
            "",
            "size_t pa_builtin_app_count(void)",
            "{",
            "    return sizeof(builtin_app_ids) / sizeof(builtin_app_ids[0]);",
            "}",
            "",
            "const char *pa_builtin_app_id(size_t index)",
            "{",
            "    return index < pa_builtin_app_count() ? builtin_app_ids[index] : NULL;",
            "}",
            "",
            "const pa_builtin_app_file_t *pa_builtin_app_file_find(",
            "    const char *app_id, const char *path)",
            "{",
            "    if (!app_id || !path) return NULL;",
            "    for (size_t i = 0;",
            "         i < sizeof(builtin_app_files) / sizeof(builtin_app_files[0]);",
            "         ++i) {",
            "        const pa_builtin_app_file_t *file = &builtin_app_files[i];",
            "        if (strcmp(file->app_id, app_id) == 0 &&",
            "            strcmp(file->path, path) == 0) return file;",
            "    }",
            "    return NULL;",
            "}",
            "",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--app", action="append", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    generate(args.app, args.output)


if __name__ == "__main__":
    main()
