#!/usr/bin/env python3
"""Prepare deterministic, gzip-compressed, dependency-free web assets."""

import argparse
import gzip
from pathlib import Path

ROUTES = {
    "index.html": ["/", "/index.html"],
    "css/app.css": ["/system/app.css"],
    "js/pocket-arcade.js": ["/system/pocket-arcade.js"],
    "js/app.js": ["/system/app.js"],
    "assets/icon.svg": ["/assets/system/icon.svg"],
}

MIME = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
}


def c_bytes(data: bytes) -> str:
    lines = []
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(lines)


def generate(input_dir: Path, output: Path) -> None:
    assets = []
    for relative, routes in ROUTES.items():
        source = input_dir / relative
        raw = source.read_bytes()
        # Keep the navigation document uncompressed for compatibility with
        # minimal captive-portal browsers. Larger subresources remain gzip.
        encoding = None if source.suffix == ".html" else "gzip"
        prepared = (
            gzip.compress(raw, compresslevel=9, mtime=0)
            if encoding
            else raw
        )
        assets.append((relative, routes, MIME[source.suffix], encoding, prepared))

    parts = [
        "/* Generated by tools/prepare_web.py. Do not edit. */",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        "typedef struct {",
        "    const char *path;",
        "    const char *mime;",
        "    const char *encoding;",
        "    const unsigned char *data;",
        "    size_t length;",
        "} pa_web_asset_t;",
        "",
    ]
    entries = []
    for index, (_, routes, mime, encoding, data) in enumerate(assets):
        symbol = f"asset_{index}"
        parts += [
            f"static const unsigned char {symbol}[] = {{",
            c_bytes(data),
            "};",
            "",
        ]
        for route in routes:
            encoding_literal = f'"{encoding}"' if encoding else "NULL"
            entries.append(
                f'    {{ "{route}", "{mime}", {encoding_literal}, '
                f"{symbol}, sizeof({symbol}) }},"
            )
    parts += [
        "static const pa_web_asset_t assets[] = {",
        *entries,
        "};",
        "",
        "const pa_web_asset_t *pa_web_asset_find(const char *path)",
        "{",
        "    for (size_t i = 0; i < sizeof(assets) / sizeof(assets[0]); ++i) {",
        "        if (strcmp(assets[i].path, path) == 0) return &assets[i];",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    generate(args.input, args.output)


if __name__ == "__main__":
    main()
